name: build

on:
  push:
    branches: [ "master" ]
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.props'
  pull_request:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.props'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: KSPModdingLibs/KSPBuildTools/.github/workflows/build.yml@0.0.4
    with:
      use-ckan: true
